name: Rust Continuous Integration

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
        submodules: recursive
    - name: Build
      run: cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
        submodules: recursive
    - name: Test
      run: cargo test

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
        submodules: recursive
    - name: Format
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
        submodules: recursive
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings
